In [1]:
import os
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
# Import and Combine all Fake, Genuine and Cloned Datasets

fake_dir = Path("/Volumes/E$/CEIR/Clean Dumps/Fake")
genuine_dir = Path("/Volumes/E$/CEIR/Clean Dumps/Genuine")
cloned_dir = Path("/Volumes/E$/CEIR/Clean Dumps/Cloned")

fake_df = pd.concat(
    (pd.read_parquet(f) for f in sorted(fake_dir.glob("*.parquet"))),
    ignore_index=True
)

genuine_df = pd.concat(
    (pd.read_parquet(f) for f in sorted(genuine_dir.glob("*.parquet"))),
    ignore_index=True
)


print(f"Fake: {len(fake_df):,} rows | Genuine: {len(genuine_df):,} rows")

Fake: 2,797,867 rows | Genuine: 66,815,713 rows

In [3]:
fake_df.head()

,imei_first_seen,last_seen,imei,imei_status,imsi,msisdn,rat,cgi,id_type,id_number,prefix,mno,gender,birth_year,age,district,mcc,country
0,2025-08-31 21:22:51,1970-01-01 00:00:00,00000000001258,,,,1,641-10-1234-5678,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,,UNKNOWN
1,2025-08-31 21:44:33,2026-05-22 14:27:00,00100383911812,W,641101937102014,256764133292,,,NATIONAL_ID,CM940241019NKJ,076,MTN,Male,1994,32,MASAKA,641,Uganda
2,2025-08-31 21:42:40,2026-03-08 00:19:33,00100711652262,W,641010410142340,,,,NaN,NaN,NaN,AIRTEL,NaN,<NA>,<NA>,NaN,641,Uganda
3,2025-08-07 18:38:50,2026-05-22 10:57:32,00353464268547,W,641101943627167,256785614758,,,NATIONAL_ID,CM940031023TPK,078,MTN,Male,1994,32,BUNDIBUGYO,641,Uganda
4,2025-08-31 21:47:40,2026-05-22 17:32:00,00431002975819,W,641101967558963,256790809987,,,NATIONAL_ID,CM0406610434KA,0790,MTN,Male,2004,22,KOBOKO,641,Uganda

In [4]:
#drop uneccessary columns
fake_df = fake_df.drop(columns=['last_seen','imei_status','imsi','msisdn','rat','cgi','id_type','id_number','prefix','mno', 'gender', 'birth_year', 'age', 'district', 'mcc', 'country'])
genuine_df = genuine_df.drop(columns=['last_seen','imei_status','imsi','msisdn','rat','cgi','id_type','id_number','prefix','mno', 'gender', 'birth_year', 'age', 'district', 'mcc', 'country', 'tac', 'oem', 'brand','model', 'marketing_name',  'os_family', 'os_version', 'sim_slots', 'has_2g', 'has_3g', 'has_4g', 'has_5g', 'year_released'])

In [5]:
fake_df = fake_df[
    (fake_df['imei_first_seen'] >= '2026-06-01') &
    (fake_df['imei_first_seen'] <  '2026-07-01')
].reset_index(drop=True)

In [6]:
genuine_df = genuine_df[
    (genuine_df['imei_first_seen'] >= '2026-06-01') &
    (genuine_df['imei_first_seen'] <  '2026-07-01')
].reset_index(drop=True)

In [7]:
fake_df['imei'].count()

np.int64(69744)

In [8]:
genuine_df['imei'].count()

np.int64(814538)

In [9]:
genuine_df.head()

      imei_first_seen            imei                 device_type
0 2026-06-04 07:32:54  35522177900139  Mobile Phone/Feature phone
1 2026-06-03 23:16:17  35522177906413  Mobile Phone/Feature phone
2 2026-06-04 12:25:31  35522177907539  Mobile Phone/Feature phone
3 2026-06-04 00:37:31  35522177907747  Mobile Phone/Feature phone
4 2026-06-08 15:38:13  35522177897581  Mobile Phone/Feature phone

In [10]:
df=genuine_df['device_type'].value_counts().reset_index(name='count')

In [11]:
df.head(15)

                                          device_type   count
0                          Mobile Phone/Feature phone  514800
1                                          Smartphone  263699
2                                               Modem   12906
3                                            Handheld    9003
4                                          IoT Device    5091
5                                              Tablet    3437
6                                         WLAN Router    2484
7                                              Dongle    1312
8                               Portable(include PDA)     843
9                                            Wearable     317
10                                             Module     257
11                                            Vehicle     155
12                                 Connected Computer     122
13  Device for the Automatic Processing of Data (APD)     112