In [1]:
import pandas as pd

df_10_25 = pd.read_pickle("/Volumes/KYC Dumps/Pickle Files/Cleaned Files/df_10_25.pkl")
df_11_25 = pd.read_pickle("/Volumes/KYC Dumps/Pickle Files/Cleaned Files/df_11_25.pkl")
df_12_25 = pd.read_pickle("/Volumes/KYC Dumps/Pickle Files/Cleaned Files/df_12_25.pkl")
df_01_26 = pd.read_pickle("/Volumes/KYC Dumps/Pickle Files/Cleaned Files/df_01_26.pkl")

In [1]:
df_10_25[df_10_25["msisdn"].astype(str) == "0200913126"]

NameError: name 'df_10_25' is not defined

In [3]:
df_11_25[df_11_25["msisdn"].astype(str) == "0200913126"]

Empty DataFrame
Columns: [msisdn, first_name, surname, id_type, id_number, prefix, MNO]
Index: []

In [4]:
df_12_25[df_12_25["msisdn"].astype(str) == "0200913126"]

Empty DataFrame
Columns: [msisdn, first_name, surname, id_type, id_number, prefix, MNO]
Index: []

In [5]:
df_01_26[df_01_26["msisdn"].astype(str) == "0200913126"]

,msisdn,first_name,surname,id_type,id_number,prefix,MNO
43729621,0200913126,EDWARD,KAYE,NATIONAL_ID,CM8405210066MH,0200,AIRTEL